services:
  backend:
    image: 265751834194.dkr.ecr.ap-south-1.amazonaws.com/profiilo-be:latest
    container_name: profilio-backend

    ports:
      - "127.0.0.1:5000:5000"

    env_file:
      - .env

    restart: unless-stopped

    networks:
      - profilio-network

networks:
  profilio-network:
    external: true
